<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- REPORT GENERATOR -->
<!DOCTYPE THESAURUS [
<!ELEMENT THESAURUS (CONCEPT+)>
<!ELEMENT CONCEPT ( (DESCRIPTOR|NON-DESCRIPTOR),SC*,SN*,UF*,USE*,BT*,NT*,RT*,STA*,INP*,APP*,UPD*,NVD*,TNR*,FLG*,Personalnote*)>
<!ELEMENT DESCRIPTOR (#PCDATA)>
<!ELEMENT NON-DESCRIPTOR (#PCDATA)>
<!ELEMENT SC (#PCDATA)>
<!ELEMENT SN (#PCDATA)>
<!ELEMENT UF (#PCDATA)>
<!ELEMENT USE (#PCDATA)>
<!ELEMENT BT (#PCDATA)>
<!ELEMENT NT (#PCDATA)>
<!ELEMENT RT (#PCDATA)>
<!ELEMENT STA (#PCDATA)>
<!ELEMENT INP (#PCDATA)>
<!ELEMENT APP (#PCDATA)>
<!ELEMENT UPD (#PCDATA)>
<!ELEMENT NVD (#PCDATA)>
<!ELEMENT TNR (#PCDATA)>
<!ELEMENT FLG (#PCDATA)>
<!ELEMENT Personalnote (#PCDATA)>
]>

<THESAURUS>
<CONCEPT>
 <DESCRIPTOR>abandoned buildings</DESCRIPTOR>
 <RT>cities</RT>
 <RT>housing conditions</RT>
 <RT>property</RT>
 <RT>property values</RT>
 <RT>real estate</RT>
 <RT>slums</RT>
 <RT>urban decline</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>abduction</NON-DESCRIPTOR>
 <USE>kidnapping</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>ability</DESCRIPTOR>
 <UF>talent</UF>
 <NT>academic ability</NT>
 <NT>competence</NT>
 <NT>leadership</NT>
 <NT>skills</NT>
 <RT>achievement</RT>
 <RT>ambition</RT>
 <RT>aptitude</RT>
 <RT>aspirations</RT>
 <RT>performance</RT>
 <RT>qualifications</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Abolition movement</DESCRIPTOR>
 <BT>social movements</BT>
 <RT>American Civil War</RT>
 <RT>slavery</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abortion</DESCRIPTOR>
 <RT>abortion clinics</RT>
 <RT>birth</RT>
 <RT>birth control</RT>
 <RT>family planning</RT>
 <RT>miscarriages</RT>
 <RT>Planned Parenthood</RT>
 <RT>pregnancy</RT>
 <RT>pro-choice movement</RT>
 <RT>pro-life movement</RT>
 <RT>sexual behavior</RT>
 <RT>teenage pregnancies</RT>
 <RT>unwanted pregnancies</RT>
 <RT>women</RT>
 <RT>womens health care</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abortion clinics</DESCRIPTOR>
 <RT>abortion</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>abortion rights movement</NON-DESCRIPTOR>
 <USE>pro-choice movement</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>absent without leave</NON-DESCRIPTOR>
 <USE>military desertion</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absentee ballots</DESCRIPTOR>
 <RT>absentee voters</RT>
 <RT>absentee votes</RT>
 <RT>voting behavior</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absentee voters</DESCRIPTOR>
 <RT>absentee ballots</RT>
 <RT>absentee votes</RT>
 <RT>voters</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>absentee votes</DESCRIPTOR>
 <SN>Votes cast by persons who are absent from their
usual voting district and permitted to vote by
mail.</SN>
 <RT>absentee ballots</RT>
 <RT>absentee voters</RT>
 <RT>voting behavior</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abuse</DESCRIPTOR>
 <BT>offenses</BT>
 <NT>child abuse</NT>
 <NT>elder abuse</NT>
 <NT>emotional abuse</NT>
 <NT>sexual abuse</NT>
 <NT>spouse abuse</NT>
 <NT>substance abuse</NT>
 <RT>abuse allegations</RT>
 <RT>assault</RT>
 <RT>battered women</RT>
 <RT>deviance</RT>
 <RT>domestic violence</RT>
 <RT>family violence</RT>
 <RT>interpersonal conflict</RT>
 <RT>violence</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abuse allegations</DESCRIPTOR>
 <RT>abuse</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>abused children</DESCRIPTOR>
 <BT>juveniles</BT>
 <RT>child abuse</RT>
 <RT>family violence</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ACA</NON-DESCRIPTOR>
 <USE>Affordable Care Act</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic ability</DESCRIPTOR>
 <BT>ability</BT>
 <RT>academic achievement</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic achievement</DESCRIPTOR>
 <BT>achievement</BT>
 <RT>academic ability</RT>
 <RT>academic standards</RT>
 <RT>educational testing</RT>
 <RT>educationally disadvantaged</RT>
 <RT>knowledge level</RT>
 <RT>student evaluation</RT>
 <RT>students</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic degrees</DESCRIPTOR>
 <UF>college degrees</UF>
 <BT>credentials</BT>
 <NT>associate degrees</NT>
 <NT>bachelors degrees</NT>
 <NT>doctoral degrees</NT>
 <NT>masters degrees</NT>
 <RT>academic disciplines</RT>
 <RT>academic guidance counseling</RT>
 <RT>college faculty</RT>
 <RT>college graduates</RT>
 <RT>earned degrees</RT>
 <RT>employment qualifications</RT>
 <RT>higher education</RT>
 <RT>universities</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic disciplines</DESCRIPTOR>
 <NT>forensic sciences</NT>
 <NT>genetics</NT>
 <NT>humanities</NT>
 <NT>information science</NT>
 <NT>mathematics</NT>
 <NT>medicine</NT>
 <NT>natural sciences</NT>
 <NT>neuroscience</NT>
 <NT>social sciences</NT>
 <NT>social studies</NT>
 <RT>academic degrees</RT>
 <RT>education</RT>
 <RT>science</RT>
 <RT>scientific research</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic freedom</DESCRIPTOR>
 <BT>freedom</BT>
 <RT>education</RT>
 <RT>educational environment</RT>
 <RT>information dissemination</RT>
 <RT>intellectual freedom</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic guidance counseling</DESCRIPTOR>
 <BT>counseling</BT>
 <RT>academic degrees</RT>
 <RT>career goals</RT>
 <RT>college students</RT>
 <RT>higher education</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic libraries</DESCRIPTOR>
 <BT>libraries</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Academic Progress Rate</DESCRIPTOR>
 <UF>APR</UF>
 <RT>student athletes</RT>
 <RT>student retention</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic standards</DESCRIPTOR>
 <BT>standards</BT>
 <RT>academic achievement</RT>
 <RT>accreditation (institutions)</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>academic tenure</DESCRIPTOR>
 <UF>tenure</UF>
 <RT>college faculty</RT>
 <RT>teaching (occupation)</RT>
 <RT>universities</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>access to arts</DESCRIPTOR>
 <RT>arts</RT>
 <RT>arts audiences</RT>
 <RT>arts education</RT>
 <RT>arts facilities</RT>
 <RT>arts participation</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>access to care</NON-DESCRIPTOR>
 <USE>health care access</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>access to information</DESCRIPTOR>
 <RT>freedom of information</RT>
 <RT>information</RT>
 <RT>information dissemination</RT>
 <RT>information literacy</RT>
 <RT>information policy</RT>
 <RT>information services</RT>
 <RT>information systems</RT>
 <RT>information transfer</RT>
 <RT>information use</RT>
 <RT>libraries</RT>
 <RT>privacy</RT>
 <RT>public information</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accessibility (for disabled)</DESCRIPTOR>
 <SN>Refers to those features or characteristics of
facilities, programs, services, and technologies
that allow them to be used by individuals with
disabilities.</SN>
 <RT>Americans with Disabilities Act (1990)</RT>
 <RT>assistive devices</RT>
 <RT>disabilities</RT>
 <RT>disability discrimination</RT>
 <RT>disabled persons</RT>
 <RT>facilities</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accident prevention</DESCRIPTOR>
 <RT>public safety</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accidental death</DESCRIPTOR>
 <RT>death</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accidents</DESCRIPTOR>
 <NT>traffic accidents</NT>
 <RT>disasters</RT>
 <RT>emergencies</RT>
 <RT>emergency departments</RT>
 <RT>emergency services</RT>
 <RT>fatalities</RT>
 <RT>fires</RT>
 <RT>health</RT>
 <RT>injuries</RT>
 <RT>occupational safety and health</RT>
 <RT>public safety</RT>
 <RT>workers compensation insurance</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>accreditation (institutions)</DESCRIPTOR>
 <BT>certification</BT>
 <RT>academic standards</RT>
 <RT>quality control</RT>
 <RT>standards</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acculturation</DESCRIPTOR>
 <SN>Process of adopting cultural traits or social
patterns of another group; also, a restructuring
or blending of cultures resulting from this.</SN>
 <RT>cultural conflict</RT>
 <RT>cultural identity</RT>
 <RT>cultural pluralism</RT>
 <RT>cultural values</RT>
 <RT>culture change</RT>
 <RT>ethnic groups</RT>
 <RT>indigenous peoples</RT>
 <RT>population migration</RT>
 <RT>social integration</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>achievement</DESCRIPTOR>
 <NT>academic achievement</NT>
 <RT>ability</RT>
 <RT>achievement tests</RT>
 <RT>ambition</RT>
 <RT>aptitude</RT>
 <RT>aspirations</RT>
 <RT>competence</RT>
 <RT>credentials</RT>
 <RT>evaluation</RT>
 <RT>failure</RT>
 <RT>goals</RT>
 <RT>motivation</RT>
 <RT>performance</RT>
 <RT>standards</RT>
 <RT>success</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>achievement tests</DESCRIPTOR>
 <SN>Tests used to measure knowledge, abilities,
understanding, or skills acquired from academic
work.</SN>
 <BT>testing and measurement</BT>
 <RT>achievement</RT>
 <RT>educational testing</RT>
 <RT>performance based assessment</RT>
 <RT>standardized tests</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ACLU</NON-DESCRIPTOR>
 <USE>American Civil Liberties Union</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Acquired Immune Deficiency Syndrome</NON-DESCRIPTOR>
 <USE>AIDS</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>acquittals</DESCRIPTOR>
 <SN>Findings by a court that a defendant should not be
held responsible for the offense tried for, and
may be released from custody.</SN>
 <RT>juries</RT>
 <RT>pleas</RT>
 <RT>trials</RT>
 <RT>verdicts</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>active duty</DESCRIPTOR>
 <RT>military officers</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>activism</DESCRIPTOR>
 <SN>The practice of vigorous action or involvement as
a means of achieving political or social goals.</SN>
 <NT>judicial activism</NT>
 <NT>political activism</NT>
 <NT>social activism</NT>
 <RT>advocacy</RT>
 <RT>citizen participation</RT>
 <RT>civic engagement</RT>
 <RT>community participation</RT>
 <RT>organizations</RT>
 <RT>participation</RT>
 <RT>political opposition</RT>
 <RT>protest demonstrations</RT>
 <RT>public interest</RT>
 <RT>public interest groups</RT>
 <RT>social movements</RT>
 <RT>social protest</RT>
 <RT>volunteers</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>activities of daily living</DESCRIPTOR>
 <SN>Basic personal care tasks used to measure
functional ability in older adults.</SN>
 <UF>ADL</UF>
 <RT>aging</RT>
 <RT>caregivers</RT>
 <RT>everyday life</RT>
 <RT>geriatrics</RT>
 <RT>independent living</RT>
 <RT>physical limitations</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>actors</DESCRIPTOR>
 <BT>artists</BT>
 <RT>arts</RT>
 <RT>performing arts</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>acute myocardial infarction</NON-DESCRIPTOR>
 <USE>heart attack</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ADAM</NON-DESCRIPTOR>
 <USE>ADAM/DUF Program</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>ADAM/DUF Program</DESCRIPTOR>
 <SN>A program that measures trends in drug use among
persons arrested and booked in the United States.</SN>
 <UF>ADAM</UF>
 <UF>Arrestee Drug Abuse Monitoring program</UF>
 <UF>Drug Use Forecasting</UF>
 <UF>DUF</UF>
 <RT>drug abuse</RT>
 <RT>drug testing</RT>
 <RT>drug treatment</RT>
 <RT>drug use</RT>
 <RT>trends</RT>
 <RT>urinalysis</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adaptation</DESCRIPTOR>
 <RT>mental health</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>addiction</DESCRIPTOR>
 <UF>chemical dependence</UF>
 <NT>alcoholism</NT>
 <NT>drug dependence</NT>
 <RT>alcohol abuse</RT>
 <RT>deviance</RT>
 <RT>drug abuse</RT>
 <RT>eating disorders</RT>
 <RT>gambling</RT>
 <RT>mental disorders</RT>
 <RT>smoking</RT>
 <RT>substance abuse</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ADEA</NON-DESCRIPTOR>
 <USE>Age Discrimination in Employment Act (1967-USA)</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adjustment</DESCRIPTOR>
 <NT>loss adjustment</NT>
 <NT>personal adjustment</NT>
 <NT>prison adjustment</NT>
 <NT>retirement adjustment</NT>
 <NT>social adjustment</NT>
 <RT>coping</RT>
 <RT>deinstitutionalization</RT>
 <RT>human behavior</RT>
 <RT>life events</RT>
 <RT>life satisfaction</RT>
 <RT>mental health</RT>
 <RT>morale</RT>
 <RT>postrelease programs</RT>
 <RT>psychological wellbeing</RT>
 <RT>rehabilitation</RT>
 <RT>social change</RT>
 <RT>social reintegration</RT>
 <RT>stress</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ADL</NON-DESCRIPTOR>
 <USE>activities of daily living</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administration</DESCRIPTOR>
 <NT>educational administration</NT>
 <NT>presidential administrations</NT>
 <NT>prison administration</NT>
 <NT>public administration</NT>
 <RT>administrative costs</RT>
 <RT>administrative elites</RT>
 <RT>administrators</RT>
 <RT>budgets</RT>
 <RT>management</RT>
 <RT>planning</RT>
 <RT>policies and procedures</RT>
 <RT>policy</RT>
 <RT>policy making</RT>
 <RT>records</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administrative costs</DESCRIPTOR>
 <BT>costs</BT>
 <RT>administration</RT>
 <RT>budgets</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administrative divisions</DESCRIPTOR>
 <BT>human settlements</BT>
 <NT>arrondissements</NT>
 <NT>boroughs</NT>
 <NT>cities</NT>
 <NT>communes</NT>
 <NT>counties</NT>
 <NT>prefectures</NT>
 <NT>provinces</NT>
 <NT>states (USA)</NT>
 <NT>towns</NT>
 <NT>townships</NT>
 <RT>census divisions</RT>
 <RT>census regions</RT>
 <RT>demographic characteristics</RT>
 <RT>local government</RT>
 <RT>metropolitan areas</RT>
 <RT>population dynamics</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administrative elites</DESCRIPTOR>
 <RT>administration</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>administrative records</NON-DESCRIPTOR>
 <USE>records</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>administrators</DESCRIPTOR>
 <RT>administration</RT>
 <RT>leadership</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>admissions policies</DESCRIPTOR>
 <BT>educational policy</BT>
 <RT>Affirmative Action</RT>
 <RT>educational opportunities</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adolescents</DESCRIPTOR>
 <UF>teenagers</UF>
 <BT>age groups</BT>
 <RT>children</RT>
 <RT>delinquent behavior</RT>
 <RT>juveniles</RT>
 <RT>teenage parents</RT>
 <RT>teenage pregnancies</RT>
 <RT>young adults</RT>
 <RT>youthful offenders</RT>
 <RT>youths</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adopted children</DESCRIPTOR>
 <RT>adoption</RT>
 <RT>child welfare</RT>
 <RT>children</RT>
 <RT>illegal adoption</RT>
 <RT>parents</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adoption</DESCRIPTOR>
 <RT>adopted children</RT>
 <RT>adoptive parents</RT>
 <RT>child rearing</RT>
 <RT>child welfare</RT>
 <RT>children</RT>
 <RT>families</RT>
 <RT>illegal adoption</RT>
 <RT>parents</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adoption leave</DESCRIPTOR>
 <BT>family leave</BT>
 <RT>maternity leave</RT>
 <RT>paternity leave</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adoptive parents</DESCRIPTOR>
 <BT>parents</BT>
 <RT>adoption</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult care services</DESCRIPTOR>
 <UF>day care services</UF>
 <BT>supportive services</BT>
 <RT>caregivers</RT>
 <RT>eldercare</RT>
 <RT>home care</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult children</DESCRIPTOR>
 <SN>Refers to adults in relationship to their parents;
e.g. as caregivers of elderly or ill parents.</SN>
 <BT>family relationships</BT>
 <RT>adults</RT>
 <RT>caregiver burden</RT>
 <RT>family life</RT>
 <RT>inlaws</RT>
 <RT>intergenerational relations</RT>
 <RT>parents</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult education</DESCRIPTOR>
 <SN>Provision of learning opportunites to adults in
professional, vocational, personal, and social
development.</SN>
 <BT>education</BT>
 <RT>adult literacy</RT>
 <RT>adults</RT>
 <RT>basic skills</RT>
 <RT>community colleges</RT>
 <RT>continuing education</RT>
 <RT>high school equivalency programs</RT>
 <RT>literacy education</RT>
 <RT>postsecondary education</RT>
 <RT>professional development</RT>
 <RT>training</RT>
 <RT>vocational education</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult literacy</DESCRIPTOR>
 <BT>literacy</BT>
 <RT>adult education</RT>
 <RT>adult reading programs</RT>
 <RT>adults</RT>
 <RT>functional literacy</RT>
 <RT>literacy education</RT>
 <RT>reading skills</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult offenders</DESCRIPTOR>
 <BT>offenders</BT>
 <RT>adults</RT>
 <RT>correctional facilities (adults)</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adult reading programs</DESCRIPTOR>
 <BT>reading programs</BT>
 <RT>adult literacy</RT>
 <RT>functional literacy</RT>
 <RT>literacy education</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adultery</DESCRIPTOR>
 <RT>divorce</RT>
 <RT>marital instability</RT>
 <RT>marital relations</RT>
 <RT>marriage</RT>
 <RT>sexual behavior</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>adults</DESCRIPTOR>
 <BT>age groups</BT>
 <RT>adult children</RT>
 <RT>adult education</RT>
 <RT>adult literacy</RT>
 <RT>adult offenders</RT>
 <RT>family life</RT>
 <RT>fathers</RT>
 <RT>mothers</RT>
 <RT>older adults</RT>
 <RT>parents</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>advertising</DESCRIPTOR>
 <NT>political advertising</NT>
 <NT>public service advertising</NT>
 <RT>consumer advocates</RT>
 <RT>consumers</RT>
 <RT>marketing</RT>
 <RT>mass media</RT>
 <RT>media influence</RT>
 <RT>persuasion</RT>
 <RT>public relations</RT>
 <RT>publicity</RT>
 <RT>retail industry</RT>
 <RT>social influences</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>advocacy</DESCRIPTOR>
 <SN>Active support for and representation of an
individual, group or cause.</SN>
 <UF>citizen advocacy</UF>
 <NT>animal rights advocates</NT>
 <NT>child advocacy</NT>
 <NT>consumer advocates</NT>
 <RT>activism</RT>
 <RT>citizen participation</RT>
 <RT>legal aid</RT>
 <RT>organizations</RT>
 <RT>public interest</RT>
 <RT>public interest groups</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aerospace industry</DESCRIPTOR>
 <BT>industry</BT>
 <RT>space exploration</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Affirmative Action</DESCRIPTOR>
 <SN>A policy to increase opportunities for women and
minorities, particularly in the context of
employment and education.</SN>
 <RT>admissions policies</RT>
 <RT>comparable worth</RT>
 <RT>discrimination</RT>
 <RT>educational opportunities</RT>
 <RT>employment discrimination</RT>
 <RT>employment practices</RT>
 <RT>Equal Employment Opportunity</RT>
 <RT>minorities</RT>
 <RT>womens rights</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>affluence</DESCRIPTOR>
 <RT>personal debt</RT>
 <RT>personal wealth</RT>
 <RT>poverty</RT>
 <RT>quality of life</RT>
 <RT>standard of living</RT>
 <RT>wealth</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Affordable Care Act</DESCRIPTOR>
 <UF>ACA</UF>
 <RT>health care access</RT>
 <RT>health care delivery</RT>
 <RT>health care reform</RT>
 <RT>health insurance</RT>
 <RT>Small Business Health Options Program</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Afghanistan War</DESCRIPTOR>
 <BT>war</BT>
 <RT>September 11 attack</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>African Americans</DESCRIPTOR>
 <UF>Afro-Americans</UF>
 <UF>Black Americans</UF>
 <UF>Blacks</UF>
 <UF>Negroes</UF>
 <BT>ethnic groups</BT>
 <RT>Black community</RT>
 <RT>Black militancy</RT>
 <RT>Black power</RT>
 <RT>Black White relations</RT>
 <RT>ghettos</RT>
 <RT>race relations</RT>
 <RT>slavery</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>African studies</DESCRIPTOR>
 <BT>area studies</BT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>Afro-Americans</NON-DESCRIPTOR>
 <USE>African Americans</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>after school programs</DESCRIPTOR>
 <BT>programs</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aftercare</DESCRIPTOR>
 <SN>Health care provided to a person after primary
treatment is completed.  Use also for follow-up
services for treatment programs such as substance
abuse treatment.</SN>
 <BT>patient care</BT>
 <RT>home care</RT>
 <RT>long term care</RT>
 <RT>post-hospitalization care</RT>
 <RT>treatment</RT>
 <RT>treatment programs</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>age</DESCRIPTOR>
 <BT>physical characteristics</BT>
 <RT>age groups</RT>
 <RT>aging population</RT>
 <RT>demographic characteristics</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>age discrimination</DESCRIPTOR>
 <UF>ageism</UF>
 <BT>discrimination</BT>
 <RT>Age Discrimination in Employment Act (1967-USA)</RT>
 <RT>aging</RT>
 <RT>attitudes toward aging</RT>
 <RT>older adults</RT>
 <RT>older workers</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Age Discrimination in Employment Act (1967-USA)</DESCRIPTOR>
 <UF>ADEA</UF>
 <BT>legislation</BT>
 <RT>age discrimination</RT>
 <RT>employment discrimination</RT>
 <RT>employment practices</RT>
 <RT>Equal Employment Opportunity</RT>
 <RT>older workers</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>age groups</DESCRIPTOR>
 <NT>adolescents</NT>
 <NT>adults</NT>
 <NT>children</NT>
 <NT>generations</NT>
 <NT>older adults</NT>
 <NT>young adults</NT>
 <RT>age</RT>
 <RT>aging population</RT>
 <RT>demographic characteristics</RT>
 <RT>intergenerational conflict</RT>
 <RT>intergenerational relations</RT>
 <RT>peer groups</RT>
 <RT>peer influence</RT>
 <RT>youths</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>aged</NON-DESCRIPTOR>
 <USE>older adults</USE>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>ageism</NON-DESCRIPTOR>
 <USE>age discrimination</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Agency for International Development</DESCRIPTOR>
 <UF>AID</UF>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aggravated assault</DESCRIPTOR>
 <SN>Unlawful application of physical force to another
with the intention of committing an additional
crime, or done with circumstances of peculiar
outrage or atrocity.</SN>
 <BT>assault</BT>
 <RT>armed robbery</RT>
 <RT>homicide</RT>
 <RT>rape</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aggression</DESCRIPTOR>
 <RT>anger</RT>
 <RT>behavior problems</RT>
 <RT>bullying</RT>
 <RT>conflict</RT>
 <RT>crime</RT>
 <RT>hostility</RT>
 <RT>interpersonal conflict</RT>
 <RT>intimidation</RT>
 <RT>invasion</RT>
 <RT>militarism</RT>
 <RT>threats</RT>
 <RT>violence</RT>
 <RT>war</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aging</DESCRIPTOR>
 <UF>old age</UF>
 <BT>life cycle</BT>
 <RT>activities of daily living</RT>
 <RT>age discrimination</RT>
 <RT>Alzheimers disease</RT>
 <RT>caregiver burden</RT>
 <RT>elder abuse</RT>
 <RT>eldercare</RT>
 <RT>geriatrics</RT>
 <RT>gerontology</RT>
 <RT>older adults</RT>
 <RT>physical limitations</RT>
 <RT>retirees</RT>
 <RT>retirement</RT>
 <RT>senility</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aging population</DESCRIPTOR>
 <SN>Refers to the increased proportion of the older
adult population, as influenced by birth and death
rates, and immigration.</SN>
 <BT>populations</BT>
 <RT>age</RT>
 <RT>age groups</RT>
 <RT>birth rates</RT>
 <RT>demographic characteristics</RT>
 <RT>mortality rates</RT>
 <RT>population migration</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agrarian reform</DESCRIPTOR>
 <UF>land reform</UF>
 <RT>agricultural policy</RT>
 <RT>agriculture</RT>
 <RT>land distribution</RT>
 <RT>land tenure</RT>
 <RT>rural areas</RT>
 <RT>rural development</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>agrarian workers</NON-DESCRIPTOR>
 <USE>agricultural workers</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agribusiness</DESCRIPTOR>
 <BT>businesses</BT>
 <RT>agriculture</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural census</DESCRIPTOR>
 <RT>agriculture</RT>
 <RT>farm families</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural development</DESCRIPTOR>
 <RT>agriculture</RT>
 <RT>developing nations</RT>
 <RT>economic development</RT>
 <RT>international development</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural land</DESCRIPTOR>
 <RT>agriculture</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural markets</DESCRIPTOR>
 <RT>agriculture</RT>
 <RT>livestock</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural organizations</DESCRIPTOR>
 <RT>agriculture</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural policy</DESCRIPTOR>
 <BT>economic policy</BT>
 <RT>agrarian reform</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural production</DESCRIPTOR>
 <RT>agricultural productivity</RT>
 <RT>agriculture</RT>
 <RT>commodities</RT>
 <RT>droughts</RT>
 <RT>food production</RT>
 <RT>livestock</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural productivity</DESCRIPTOR>
 <RT>agricultural production</RT>
 <RT>agriculture</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural services</DESCRIPTOR>
 <RT>agriculture</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural workers</DESCRIPTOR>
 <UF>agrarian workers</UF>
 <RT>agriculture</RT>
 <RT>farm families</RT>
 <RT>farm workers</RT>
 <RT>farmers</RT>
 <RT>farms</RT>
 <RT>migrant workers</RT>
 <RT>rural population</RT>
 <RT>seasonal labor</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agricultural zones</DESCRIPTOR>
 <RT>agriculture</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>agriculture</DESCRIPTOR>
 <NT>crops</NT>
 <NT>farms</NT>
 <NT>livestock</NT>
 <RT>agrarian reform</RT>
 <RT>agribusiness</RT>
 <RT>agricultural census</RT>
 <RT>agricultural development</RT>
 <RT>agricultural land</RT>
 <RT>agricultural markets</RT>
 <RT>agricultural organizations</RT>
 <RT>agricultural production</RT>
 <RT>agricultural productivity</RT>
 <RT>agricultural services</RT>
 <RT>agricultural workers</RT>
 <RT>agricultural zones</RT>
 <RT>commodities</RT>
 <RT>farm families</RT>
 <RT>farm workers</RT>
 <RT>farmers</RT>
 <RT>food industry</RT>
 <RT>food production</RT>
 <RT>rural population</RT>
</CONCEPT>

<CONCEPT>
 <NON-DESCRIPTOR>AID</NON-DESCRIPTOR>
 <USE>Agency for International Development</USE>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>AIDS</DESCRIPTOR>
 <UF>Acquired Immune Deficiency Syndrome</UF>
 <BT>disease</BT>
 <RT>communicable diseases</RT>
 <RT>gays and lesbians</RT>
 <RT>HIV</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>air bases</DESCRIPTOR>
 <BT>military bases</BT>
 <RT>missile bases</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>air pollution</DESCRIPTOR>
 <BT>pollution</BT>
 <NT>fuel emissions</NT>
 <RT>climate</RT>
 <RT>global warming</RT>
 <RT>greenhouse effect</RT>
 <RT>industrial pollution</RT>
 <RT>pollution control</RT>
 <RT>urban areas</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>air transportation</DESCRIPTOR>
 <BT>transportation</BT>
 <NT>airports</NT>
 <RT>air travel</RT>
 <RT>aircraft</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>air travel</DESCRIPTOR>
 <BT>travel</BT>
 <RT>air transportation</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aircraft</DESCRIPTOR>
 <BT>vehicles</BT>
 <RT>air transportation</RT>
 <RT>aircraft hijackings</RT>
 <RT>aircraft security</RT>
 <RT>airport security</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aircraft hijackings</DESCRIPTOR>
 <BT>hijacking</BT>
 <RT>aircraft</RT>
 <RT>aircraft security</RT>
 <RT>airport security</RT>
 <RT>hostages</RT>
 <RT>kidnapping</RT>
 <RT>terrorist kidnappings</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>aircraft security</DESCRIPTOR>
 <BT>security</BT>
 <RT>aircraft</RT>
 <RT>aircraft hijackings</RT>
 <RT>airport security</RT>
 <RT>security systems</RT>
 <RT>surveillance equipment</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>airport security</DESCRIPTOR>
 <BT>security</BT>
 <RT>aircraft</RT>
 <RT>aircraft hijackings</RT>
 <RT>aircraft security</RT>
 <RT>security systems</RT>
 <RT>surveillance equipment</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>airports</DESCRIPTOR>
 <BT>air transportation</BT>
 <RT>transport infrastructure</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>al Qaeda</DESCRIPTOR>
 <RT>religious fundamentalism</RT>
 <RT>September 11 attack</RT>
 <RT>terrorism</RT>
 <RT>terrorist attacks</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>alarm systems</DESCRIPTOR>
 <RT>security systems</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>Alaskan Natives</DESCRIPTOR>
 <BT>ethnic groups</BT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>alcohol</DESCRIPTOR>
 <RT>alcohol abuse</RT>
 <RT>alcohol consumption</RT>
 <RT>alcoholism</RT>
 <RT>drinking age</RT>
 <RT>drinking behavior</RT>
 <RT>driving under the influence</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>alcohol abuse</DESCRIPTOR>
 <SN>Overuse or misuse of alcoholic beverages.  Do not
confuse with &quot;alcoholism&quot;.</SN>
 <UF>problem drinking</UF>
 <BT>substance abuse</BT>
 <RT>addiction</RT>
 <RT>alcohol</RT>
 <RT>alcohol consumption</RT>
 <RT>alcoholism</RT>
 <RT>drinking behavior</RT>
 <RT>driving under the influence</RT>
 <RT>drunkenness</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>alcohol consumption</DESCRIPTOR>
 <RT>alcohol</RT>
 <RT>alcohol abuse</RT>
 <RT>alcoholism</RT>
 <RT>drinking age</RT>
 <RT>drinking behavior</RT>
 <RT>driving under the influence</RT>
 <RT>drunkenness</RT>
 <RT>lifestyles</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>alcoholism</DESCRIPTOR>
 <BT>addiction</BT>
 <BT>disease</BT>
 <RT>alcohol</RT>
 <RT>alcohol abuse</RT>
 <RT>alcohol consumption</RT>
 <RT>detoxification</RT>
 <RT>drinking behavior</RT>
 <RT>drug abuse</RT>
 <RT>drug dependence</RT>
 <RT>drug treatment</RT>
 <RT>drunkenness</RT>
 <RT>mental disorders</RT>
</CONCEPT>

<CONCEPT>
 <DESCRIPTOR>alienation</DESCRIPTOR>
 <SN>Loss of interrelatedness with others; estrangement
of the individual from others and/or from
prevailing values, goals, and expectations of
society.</SN>
 <BT>emotional states</BT>
 <RT>anomie</RT>
 <RT>apathy</RT>
 <RT>disenfranchisement</RT>
 <RT>hostility</RT>
 <RT>powerlessness</RT>